### ISSUE TITLE
[Question]: Custom folding after releasing `nvim-ufo`

### ISSUE THREAD

**Issue by lmburns** [kevinhwang91/dotfiles#2]
Sorry for posting this, but I was just curious as to how you had your setup now after you've released `nvim-ufo`. I use some parts of your configuration for Neovim and am somewhat confused on how I would implement `ufo` along with the existing code (mainly `AnyFold`). I wasn't sure if it would be optimal to just use the `setup()` call from `ufo`, or to run the `coc` command `ufo.foldingRange`.

Also, I was wondering if you had the same issue that I do with the `zE` binding moving the cursor one character to the left if typing starts as soon as the buffer opens? By wiping the previous folding code from here
https://github.com/kevinhwang91/dotfiles/blob/f2934e85be3abec07531780a61136e28f872c743/nvim/lua/plugs/fold.lua#L207
and just using `ufo`, I am pretty sure that the problem is gone and was solved by using `fn.winsaveview()` / `fn.winrestview(id)`

**Comment by kevinhwang91** [comment]
> I use some parts of your configuration for Neovim and am somewhat confused on how I would implement ufo along with the existing code (mainly AnyFold). 

I have uninstalled `AnyFold`, there're `lsp` and `indent` providers in nvim-ufo now, `treesitter` provider will come soon.

There were some issues with my fold config before I made nvim-ufo. You can just use nvim-ufo for now. It's powerful, no need other fold plugins.
